CREATE TABLE IF NOT EXISTS CALCBENCH.RAW.COMPANIES (
    TICKER VARCHAR,
    ENTITY_NAME VARCHAR,
    ENTITY_ID INTEGER,
    ENTITY_CODE VARCHAR,

    MOST_RECENT_FILING DATE,
    MOST_RECENT_FULL_YEAR_END DATE,

    MOST_RECENT_FISCAL_YEAR INTEGER,
    MOST_RECENT_COMPLETE_CALENDAR_YEAR INTEGER,
    MOST_RECENT_COMPLETE_FISCAL_YEAR INTEGER,
    MOST_RECENT_FILING_CALENDAR_PERIOD INTEGER,

    FIRST_FILING DATE,

    NAICS_CODE INTEGER,
    SIC_CODE INTEGER,
    SIC_CATEGORY VARCHAR,
    SIC_GROUP_MINOR_GROUP_TITLE VARCHAR,

    CIK_CODE VARCHAR,
    NAICS INTEGER,

    INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM VARCHAR DEFAULT 'CALCBENCH'
);