CREATE TABLE IF NOT EXISTS CALCBENCH.RAW.FINANCIALS (
    TICKER VARCHAR,
    METRIC VARCHAR,
    FISCAL_PERIOD VARCHAR,
    VALUE FLOAT,
    CIK VARCHAR(10),
    PERIOD_START DATE,
    PERIOD_END DATE,
    CALENDAR_YEAR INTEGER,
    CALENDAR_PERIOD INTEGER,
    INGESTED_AT TIMESTAMP_TZ,
    SOURCE_SYSTEM VARCHAR
);